# Service name determines bucket name
service: image-processor

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024
  timeout: 30
  stage: prod
  region: us-east-1
  role: BucketAccess
  apiName: ${self:service}
  environment:
    BUCKET: ${self:service}-assets
    SLS_DEBUG: "*"
    RESIZE_LAMBDA: ${self:service}-resizeImage
  deploymentBucket:
    name: ${self:provider.environment.BUCKET}

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  
functions:
  getImage:
    name: ${self:service}-getImage
    handler: src/getImage.handler
    events:
      - http: GET {proxy+}
    package:
      include:
        - src/getImage.js
  resizeImage:
    name: ${self:provider.environment.RESIZE_LAMBDA}
    handler: src/resizeImage.handler
    package:
      include:
        - src/resizeImage.js
  uploadImage:
    name: ${self:service}-uploadImage
    handler: src/uploadImage.handler
    events:
      - http: POST /upload
    package:
      include:
        - src/uploadImage.js

resources:
  Resources:
    BucketAccess:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:provider.environment.BUCKET}-S3-BUCKET-ACCESS-${self:service}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:provider.environment.BUCKET}-access-bucket-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:*"
                  Resource:
                    -  "Fn::Join": ["", ["arn:aws:s3:::", "${self:provider.environment.BUCKET}/*"]]
                - Effect: Allow
                  Action:
                    - "lambda:InvokeFunction"
                  Resource:
                    -  "Fn::Join": ["", ["arn:aws:lambda:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":function:${self:provider.environment.RESIZE_LAMBDA}"]]